"""add_shop_columns

Revision ID: 321e22c937d5
Revises: 
Create Date: 2026-05-05 00:45:04.007797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '321e22c937d5'
down_revision: Union[str, Sequence[str], None] = "0001_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('party_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('shop_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('bank_account_no', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('bank_ifsc', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('terms_line1', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('terms_line2', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop_settings', schema=None) as batch_op:
        batch_op.drop_column('terms_line2')
        batch_op.drop_column('terms_line1')
        batch_op.drop_column('bank_ifsc')
        batch_op.drop_column('bank_account_no')
        batch_op.drop_column('bank_name')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('party_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
